name: Build and Release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            platform: linux
            archive-cmd: "tar -czf"
            archive-ext: "tar.gz"
          - os: windows-latest
            platform: windows
            archive-cmd: "7z a -tzip"
            archive-ext: "zip"
          - os: macos-latest
            platform: macos
            archive-cmd: "tar -czf"
            archive-ext: "tar.gz"

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 23
      uses: actions/setup-java@v4
      with:
        java-version: '23'
        distribution: 'temurin'

    - name: Make gradlew executable
      run: chmod +x gradlew

    - name: Build application
      run: ./gradlew clean build

    - name: Create runtime image
      run: ./gradlew runtime

    - name: Create app image
      run: ./gradlew jpackage

    - name: Archive app image (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        cd build/dist
        7z a -tzip ../../VikingsChess-${{ matrix.platform }}-app.zip VikingsChess*
      shell: bash

    - name: Archive app image (Unix)
      if: matrix.os != 'windows-latest'
      run: |
        cd build/dist
        tar -czf ../../VikingsChess-${{ matrix.platform }}-app.tar.gz VikingsChess*
      shell: bash

    - name: Upload portable app to release
      uses: softprops/action-gh-release@v2
      with:
        files: VikingsChess-${{ matrix.platform }}-app.${{ matrix.archive-ext }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
